### PR TITLE
Add check for ins-completion in <C-L> mapping

### LINKED ISSUE #13: <C-L> mapping is triggered with <C-X><C-L>
When typing `<C-X><C-L>` in insert mode it is expected to trigger whole-line completions. But if this plugin is installed caps lock in insert mode is triggered.

**Expected behaviour**:
`<C-X><C-L>` - whole-line completion
`<C-L>` - caps lock

### PR DESCRIPTION
**Pull request by fedorenchik**
Closes #13.

### CODE REVIEW

**Comment by tpope** [comment]
Any reason we can't use `pumvisible()`? That's the usual idiom for this.

**Comment by fedorenchik** [comment]
I've considered this but in this case can't use `pumvisible()` because upon entering `<C-X>` there's no completion menu yet so `pumvisible()` always returns `0`.

**Comment by tpope** [comment]
I can't actually reproduce this. What version of Vim are you using?

**Comment by fedorenchik** [comment]
Vim `8.2.3113`.

```
VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Jul  6 2021 19:29:28)
Included patches: 1-3113
Compiled by leonid@sirius
Huge version with GTK3 GUI.  Features included (+) or not (-):
+acl               +file_in_path      +mouse_urxvt       -tag_any_white
-arabic            +find_in_path      +mouse_xterm       -tcl
+autocmd           +float             +multi_byte        +termguicolors
+autochdir         +folding           +multi_lang        +terminal
-autoservername    -footer            -mzscheme          +terminfo
+balloon_eval      +fork()            +netbeans_intg     +termresponse
+balloon_eval_term +gettext           +num64             +textobjects
+browse            -hangul_input      +packages          +textprop
++builtin_terms    +iconv             +path_extra        +timers
+byte_offset       +insert_expand     -perl              +title
+channel           +ipv6              +persistent_undo   +toolbar
+cindent           +job               +popupwin          +user_commands
+clientserver      +jumplist          +postscript        +vartabs
+clipboard         +keymap            +printer           +vertsplit
+cmdline_compl     +lambda            +profile           +virtualedit
+cmdline_hist      +langmap           -python            +visual
+cmdline_info      +libcall           +python3/dyn       +visualextra
+comments          +linebreak         +quickfix          +viminfo
+conceal           +lispindent        +reltime           +vreplace
+cryptv            +listcmds          -rightleft         +wildignore
+cscope            +localmap          -ruby              +wildmenu
+cursorbind        -lua               +scrollbind        +windows
+cursorshape       +menu              +signs             +writebackup
+dialog_con_gui    +mksession         +smartindent       +X11
+diff              +modify_fname      +sodium            -xfontset
+digraphs          +mouse             +sound             +xim
+dnd               +mouseshape        +spell             +xpm
-ebcdic            +mouse_dec         +startuptime       +xsmp_interact
+emacs_tags        +mouse_gpm         +statusline        +xterm_clipboard
+eval              -mouse_jsbterm     -sun_workshop      -xterm_save
+ex_extra          +mouse_netterm     +syntax            
+extra_search      +mouse_sgr         +tag_binary        
-farsi             -mouse_sysmouse    -tag_old_static    
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
  system gvimrc file: "$VIM/gvimrc"
    user gvimrc file: "$HOME/.gvimrc"
2nd user gvimrc file: "~/.vim/gvimrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
    system menu file: "$VIMRUNTIME/menu.vim"
  fall-back for $VIM: "/home/leonid/.local/share/vim"
Compilation: gcc -c -I. -Iproto -DHAVE_CONFIG_H -DFEAT_GUI_GTK -I/usr/include/gtk-3.0 -I/usr/include/pango-1.0 -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/include/harfbuzz -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/fribidi -I/usr/include/cairo -I/usr/include/lzo -I/usr/include/pixman-1 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/gio-unix-2.0 -I/usr/include/cloudproviders -I/usr/include/atk-1.0 -I/usr/include/at-spi2-atk/2.0 -I/usr/include/dbus-1.0 -I/usr/lib/dbus-1.0/include -I/usr/include/at-spi-2.0 -pthread -g -O2 -D_REENTRANT -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 
Linking: gcc -L/usr/local/lib -Wl,--as-needed -o vim -lgtk-3 -lgdk-3 -lz -lpangocairo-1.0 -lpango-1.0 -lharfbuzz -latk-1.0 -lcairo-gobject -lcairo -lgdk_pixbuf-2.0 -lgio-2.0 -lgobject-2.0 -lglib-2.0 -lSM -lICE -lXpm -lXt -lX11 -lXdmcp -lSM -lICE -lm -ltinfo -lelf -lcanberra -lsodium -lacl -lattr -lgpm -ldl 
```

**Comment by tpope** [comment]
That's newer than I have convenient access to. I'll trust that something recent in Vim is causing this breakage.

**Comment by fedorenchik** [comment]
I did some more tests. This only happens in GUI vim (I've tried gtk3). In terminal vim <C-L> works as expected without this PR.

**Comment by tpope** [comment]
Cannot reproduce in the gtk3 version ever, though my build of that is on the older side at 8.2.0716. :shrug:

**Pull request merged**
